---
title: "Ejemplos graficos ggplot"
author: "Pablo López Vaca"
date: "2024-05-27"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    collapsed: true
    smooth_scroll: true
    theme: journal
    highlight: kate
    df_print: paged
    code_folding: show
lang: es-ES
---

# Base de datos

```{r}
mtcars
```

## Estadisticas descriptivas
```{r}
summary(mtcars)
```

### Gráfico de relación entre varibles

```{r}
plot(mtcars$mpg, mtcars$wt)
```


```{r setup, include=FALSE}
# Configuración global para knitr
knitr::opts_chunk$set(echo = TRUE)

# Cargar el paquete ggplot2
library(ggplot2)
```

### Crear un gráfco de dispersión 

```{r}
# Usar el dataset integrado 'mtcars'
data(mtcars)

# Crear un gráfico de dispersión
ggplot(mtcars, aes(x = hp, y = mpg)) +
  geom_point() +
  labs(
    title = "Relación entre caballos de fuerza y millas por galón",
    x = "Caballos de fuerza",
    y = "Millas por galón"
  )
```

### Crear un gráfico de dispersión con una recta patrón

```{r}
# Usar el dataset integrado 'mtcars'
data(mtcars)

# Crear un gráfico de dispersión con una línea de tendencia
ggplot(mtcars, aes(x = hp, y = mpg)) +
  geom_point() +  # Añadir puntos de dispersión
  geom_smooth(method = "lm", se = FALSE) +  # Añadir línea de tendencia sin intervalo de confianza
  labs(
    title = "Relación entre caballos de fuerza y millas por galón",
    x = "Caballos de fuerza",
    y = "Millas por galón"
  )

```





